# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
